### ISSUE TITLE
PDA扫码没有反应

### ISSUE THREAD

**Issue by WhiteSean** [china-english/react-native-external-scan-gun#1]
你好，我这边集成后PDA扫码没有反应

**Comment by china-english** [comment]
抱歉，这么晚才看到。请问可以提供集成的代码，和使用时的代码吗？

**Comment by china-english** [comment]
PDA 扫码应该是设备内摄像头的扫码，这部分可以参考 [react-native-camera](https://github.com/react-native-camera/react-native-camera)
