### ISSUE TITLE
扫码枪扫描 ！@#¥%……&*（）——+ 等一些字符识别错误

### ISSUE THREAD

**Issue by polofish** [china-english/react-native-external-scan-gun#2]
扫码枪扫描 ！@#¥%……&*（）——+ 等一些字符识别错误

**Comment by china-english** [comment]
> 扫码枪扫描 ！@#¥%……&*（）——+ 等一些字符识别错误

暂时还不支持中文字符的扫码识别。且中文字符会导致后续字符识别错误

**Comment by polofish** [comment]
额，上面我打出来的可能是输入法不对，应该是：!@#$%^&*()_+
我尝试做了修改，可以修改下 scangunmanager.java，识别!@#$%^&*()_+这些英文状态下字符（非中文）。
希望能看下

package com.afei.scangun;

import android.util.Log;
import android.view.KeyEvent;
import static android.content.ContentValues.TAG;

public class ScanGunManager {

    private final static long MESSAGE_DELAY = 500; // 延迟500ms，判断扫码是否完成。
    private StringBuffer mStringBufferResult; // 扫码内容
    private boolean mCaps; // 大小写区分

    private ScanCodeCallback scanCodeCallback;

    public interface OnScanCodeListener {
        void onScanCode(String value);
    }


    // 类初始化时，不初始化这个对象(延时加载，真正用的时候再创建)
    private static ScanGunManager instance;

    // 构造器私有化
    private ScanGunManager(){}

    // 方法同步，调用效率低
    public static synchronized ScanGunManager getInstance(){
        if(instance==null){
            instance=new ScanGunManager();
            instance.mStringBufferResult = new StringBuffer();
        }
        return instance;
    }


    public void setReceiveCallback(ScanCodeCallback scanCodeCallback) {
        this.scanCodeCallback = scanCodeCallback;
    }

    public void clearScanBarCodeText(){
        if (mStringBufferResult!= null){
            mStringBufferResult.delete(0,mStringBufferResult.length());
        }
    }

    // 外设事件解析
    public void analysisKeyEvent(KeyEvent event) {
        int keyCode = event.getKeyCode();
        String devicesName = event.getDevice().getName();
        Log.d(TAG, "设备名称:" + devicesName);
        // 字母大小写判断
        checkLetterStatus(event);
        if (event.getAction() == KeyEvent.ACTION_DOWN) {
            char aChar = getInputCode(event);;
            if (aChar != 0) {
                if (mStringBufferResult!=null){
                    mStringBufferResult.append(aChar);
                }
            }
            if (keyCode == KeyEvent.KEYCODE_ENTER) {
                String barCode = mStringBufferResult.toString();
                if (scanCodeCallback != null) {
                    scanCodeCallback.onScanCode(barCode);
                }
                mStringBufferResult.delete(0,mStringBufferResult.length());
            }
        }
    }

    //检查shift键
    private void checkLetterStatus(KeyEvent event) {
        int keyCode = event.getKeyCode();
        if (keyCode == KeyEvent.KEYCODE_SHIFT_RIGHT || keyCode == KeyEvent.KEYCODE_SHIFT_LEFT) {
            mCaps = event.getAction() == KeyEvent.ACTION_DOWN;
        }
    }


    //获取扫描内容
    private char getInputCode(KeyEvent event) {
        int keyCode = event.getKeyCode();
        char aChar;

        if (keyCode >= KeyEvent.KEYCODE_A && keyCode <= KeyEvent.KEYCODE_Z) {
            //字母
            aChar = (char) ((mCaps ? 'A' : 'a') + keyCode - KeyEvent.KEYCODE_A);
        } else if (keyCode >= KeyEvent.KEYCODE_0 && keyCode <= KeyEvent.KEYCODE_9) {
            //数字
            if (mCaps) {
                aChar = keyValue(mCaps, keyCode);
            } else {
                aChar = (char) ('0' + keyCode - KeyEvent.KEYCODE_0);
            }
        } else {
            //其他符号
            aChar = keyValue(mCaps, keyCode);
        }
        return aChar;
    }

    /**
     * 按键对应的char表
     */
    private char keyValue(boolean caps, int keyCode) {
        switch (keyCode) {
            case KeyEvent.KEYCODE_0:
                return caps ? ')' : '0';
            case KeyEvent.KEYCODE_1:
                return caps ? '!' : '1';
            case KeyEvent.KEYCODE_2:
                return caps ? '@' : '2';
            case KeyEvent.KEYCODE_3:
                return caps ? '#' : '3';
            case KeyEvent.KEYCODE_4:
                return caps ? '$' : '4';
            case KeyEvent.KEYCODE_5:
                return caps ? '%' : '5';
            case KeyEvent.KEYCODE_6:
                return caps ? '^' : '6';
            case KeyEvent.KEYCODE_7:
                return caps ? '&' : '7';
            case KeyEvent.KEYCODE_8:
                return caps ? '*' : '8';
            case KeyEvent.KEYCODE_9:
                return caps ? '(' : '9';
            case KeyEvent.KEYCODE_NUMPAD_SUBTRACT:
                return '-';
            case KeyEvent.KEYCODE_MINUS:
                return caps ? '_' : '-';
            case KeyEvent.KEYCODE_EQUALS:
                return caps ? '+' : '=';
            case KeyEvent.KEYCODE_NUMPAD_ADD:
                return '+';
            case KeyEvent.KEYCODE_GRAVE:
                return caps ? '~' : '`';
            case KeyEvent.KEYCODE_BACKSLASH:
                return caps ? '|' : '\\';
            case KeyEvent.KEYCODE_LEFT_BRACKET:
                return caps ? '{' : '[';
            case KeyEvent.KEYCODE_RIGHT_BRACKET:
                return caps ? '}' : ']';
            case KeyEvent.KEYCODE_SEMICOLON:
                return caps ? ':' : ';';
            case KeyEvent.KEYCODE_APOSTROPHE:
                return caps ? '"' : '\'';
            case KeyEvent.KEYCODE_COMMA:
                return caps ? '<' : ',';
            case KeyEvent.KEYCODE_PERIOD:
                return caps ? '>' : '.';
            case KeyEvent.KEYCODE_SLASH:
                return caps ? '?' : '/';
            default:
                return 0;
        }
    }
}

**Comment by china-english** [comment]
首先，抱歉现在才看到并回复你。:joy:

其次关闭这个 issues 的时候，我升级了这个依赖库，并对代码进行了一些优化。2.0版本已经支持 `!@#$%^&()_+`字符的扫描识别了。:sunglasses:

非常感谢你的帮助。🙏
