### ISSUE TITLE
JS 回调没触发

### ISSUE THREAD

**Issue by littledu** [china-english/react-native-external-scan-gun#3]
```
 const eventEmitter = new NativeEventEmitter(NativeModules.ToastExample);
    const eventListener = eventEmitter.addListener(
      (scanGun as any).onScanCodeReceiveData,
      code => {
        // TODO: 扫码之后的回调
        console.log('111', code);
      },
    );
```

扫码枪扫了之后，在 item2 里可以看到输出：
<img width="41" alt="image" src="https://user-images.githubusercontent.com/1784673/178671609-e6d941d0-bf71-4854-9c7e-9c64ff8e36d9.png">
但我 JS 里面的回调并没有触发

- RN 版本：0.69

**Comment by littledu** [comment]
我用你的demo 是可以的，我再看看

**Comment by littledu** [comment]
demo 也是不可以的，但加上 TextInput ，然后把光标 focus 上,就一切正常了

**Comment by china-english** [comment]
我刚刚测试过， DEMO 不需要加任何内容就可以使用
1. 可以提供样例或者完整测试代码供我测试一下吗？
2. 运行环境： 安卓真机或虚拟机，版本号等内容

**Comment by polofish** [comment]
@littledu 检查下 你代码中监听 onScanCodeReceiveData 这个。 之前包里面修改了拼写错误“onScanCodeRecevieData”

**Comment by littledu** [comment]
@polofish @china-english 谢谢，是我使用姿势不对，这个必需配合 editText 拉起键盘扫描才行
